---
- name: Rename Windows Server
  hosts: windows
  tasks:
    - name: Set new computer name
      ansible.windows.win_hostname:
        name: SRV-DC01
      register: res

    - name: Reboot if name changed
      ansible.windows.win_reboot:
      when: res.reboot_required
